services:
  webproxy:
    image: ryannfb/nginx1.0 # Imagem Personalizada do Nginx
    ports:
      - "8080:8080"  # Expor a porta 8080
    networks:
      - wordpress
    depends_on:
      - webserver
    container_name: webproxy

  webserver:
    image: wordpress:latest  
    volumes:
      - app:/var/www/html  # Volume persistente para o Wordpress
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress
    depends_on:
      - database
    container_name: webserver

  database:
    image: mysql:5.7  # Imagem oficial do MySQL
    volumes:
      - my:/var/lib/mysql  # Volume persistente para o banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress
    container_name: database

volumes:
  app:
    name: app
  my:
    name: my

networks:
  wordpress:
    name: wordpress
